name: main
on:
  workflow_dispatch:

permissions: write-all
  #issues: write


jobs:     
  update-approvers:
    name: update-approvers
    runs-on: ubuntu-latest
#     permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
    steps:
      - uses: actions/checkout@v3
      - name: Get UserIDs
        run: |
          ls -la
          array=($(jq  '.envs | to_entries[] | .value[].userId' test.txt))
          JSON_STRING='{"reviewers":['
          for userId in ${array[@]}; do 
            JSON_STRING=$JSON_STRING'{"type":"User","id":'"$userId"'},'
          done
          JSON_STRING=$JSON_STRING']}'
          # Get the position of the last comma
          last_comma=$(echo "$JSON_STRING" | grep -aob ',' | tail -1 | cut -d':' -f1)

          # Remove the last comma from the string
          JSON_STRING=${JSON_STRING:0:last_comma}${JSON_STRING:last_comma+1}
          JSON_STRING="'"$JSON_STRING"'"
          echo $JSON_STRING
        
      - name: Deploy to production
        run: |
            echo $JSON_STRING
