name: main
on:
  workflow_dispatch:

permissions:
  issues: write


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  update-approvers:
    name: update-approvers
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        run: curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/aqeel1211/poc-codeowner-approval/environments/dev \
            -d '{"wait_timer":30,"reviewers":[{"type":"User","id":aqeel1211}]}'
