name: main
on:
  workflow_dispatch:

permissions: write-all
  #issues: write


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo building
  update-approvers:
    name: update-approvers
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
    steps:
      - name: Deploy to production
        run: |
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/aqeeleurus/poc-codeowner-approval/environments
